dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - python3
      
script:
  - export CXX=/usr/bin/g++-6 
  - export CC=/usr/bin/gcc-6
  - python3 build.py --setup --boost --relic
  - python3 build.py -- -D ENABLE_RELIC=ON -D ENABLE_ALL_OT=ON
  - ./out/build/linux/frontend/frontend_libOTe -u

