dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5


script:
  - git submodule update --init --recursive
  - export CXX=/usr/bin/g++-5
  - export CC=/usr/bin/gcc-5
  - cd cryptoTools/thirdparty/linux
  - bash all.get
  - cd ../../..
  - cmake .
  - cmake --build . -- -j

