dist: trusty
sudo: false
language: cpp

script:
  - ls
  - export CXX=/usr/local/clang-5.0.0/bin/clang
  - export CC=/usr/local/clang-5.0.0/bin/clang
  - cd cryptoTools/thirdparty/linux
  - bash all.get
  - cd ../../..
  - cmake .
  - cmake --build . -- -j
