# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, ci ]
  pull_request: {}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            submodules: recursive

      # Runs a set of commands using the runners shell
      - name: build test
        run: |
          python3 build.py --setup --relic --boost --par=4
          python3 build.py --par=4 -- -D ENABLE_ALL_OT=ON -D ENABLE_RELIC=ON 
          ./out/build/linux/frontend/frontend_libOTe -u
          

  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - uses: ilammy/msvc-dev-cmd@v1

      # Runs a set of commands using the runners shell
      - name: build test
        run: |
          python3 build.py --setup --relic --boost --par=4
          python3 build.py --par=4 -- -D ENABLE_ALL_OT=ON -D ENABLE_RELIC=ON  -G Ninja
          ./out/build/x64-Release/frontend/frontend_libOTe.exe -u
          
  #build-macOS:
  #  # The type of runner that the job will run on
  #  runs-on: macos-11.0
  #
  #  # Steps represent a sequence of tasks that will be executed as part of the job
  #  steps:
  #    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #    - uses: actions/checkout@v2
  #      with:
  #          submodules: recursive
  #
  #    # Runs a set of commands using the runners shell
  #    - name: build test
  #      run: |
  #        python3 build.py --setup --relic --boost
  #        python3 build.py --noPar -- -D ENABLE_ALL_OT=ON -D ENABLE_RELIC=ON 
  #        ./out/build/linux/frontend/frontend_libOTe -u
  #